alias dk="docker"
alias dkp="docker ps -a"
alias dki="docker images"

alias dc="docker-compose"
alias dcup="docker-compose up"
alias dcupd="docker-compose up -d"
alias dcs="docker-compose stop"
alias dcrm="docker-compose rm"
alias dck="docker-compose stop && docker-compose rm"
